### ISSUE TITLE
Apr 14, 2022 is an official holiday

### ISSUE THREAD

**Issue by larsk21** [kit-sdq/TimeSheetGenerator#118]
`The Apr 14, 2022 is an official holiday, which is not a valid working day.`

To my knowledge, "Gründonnerstag" is a school-free day, but not an offical work-free holiday in BW, Germany.

**Comment by moritzhertler** [comment]
This also applies to October 31st ("Reformationstag").

**Comment by moritzhertler** [comment]
Unfortunately, this is only stated as a note in the [api response](https://feiertage-api.de/api/?jahr=2022&nur_land=bw).
