### ISSUE TITLE
Mac Safedialog Filenames

### ISSUE THREAD

**Issue by adrianSchneider001** [kit-sdq/TimeSheetGenerator#2]
Problem with naming the Output file under Mac OSX Platform. 
Idea to solve: standard Path and Naming of the Tex file. 

See here: 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/56645708/69739020-43683e00-1137-11ea-95de-e5c38132f9a1.png">

**Comment by gstuer** [comment]
That's great to hear! I will try this again later and post whether the bug still exists on my Mac OS X.

**Comment by gstuer** [comment]
Because this error hasn't shown up for a while now, it seems to be resolved completely and as a result it will be closed for now.
