### ISSUE TITLE
JSON schemas for global.json and month.json

### ISSUE THREAD

**Issue by larsk21** [kit-sdq/TimeSheetGenerator#53]
for validation and autocomplete

**open questions**:
- [x] where should these be located? @gstuer 
  - ./examples/json-schemas ?
  - ./examples/schemas ?
  - ./json-schemas ?
  - ./json ?
  - ./schemas ?

  (important for referencing them from the example JSONs)

**Comment by larsk21** [comment]
feature is already finished, just need to know where to place the files

**Comment by larsk21** [comment]
just for clarification: the schemas are not intended to be used by our parser, but to be referenced from the users global.json and month.json s (hence the path), to provide validation and autocomplete for the user while filling in the values

**Comment by gstuer** [comment]
For me those files are an important part of the user experience and should therefore go to the examples directory (at least for now until we can provide a bigger spectrum of patterns and schemes). I would prefer ./examples/schemata or ./examples/schemes. Could you please check for the correct plural, cause i am not sure if schemas is correct :)

**Comment by larsk21** [comment]
Both "schemata" and "schemas" are correct, although in technical environments "schemas" is more common (see [here](https://json-schema.org/understanding-json-schema/reference/combining.html)) :)
