### ISSUE TITLE
Change JUnit version from 4 to 5

### ISSUE THREAD

**Issue by gstuer** [kit-sdq/TimeSheetGenerator#74]
This version change should be done in order to get access to new features, especially repeated tests. Those could get very handy for randomized test cases.

Following tasks have to be done for a successful migration process:
- [x] Evaluate the compatibility of the current JUnit4 tests and the new JUnit5 test framework
- [x] Perform the version change (Change dependencies etc.)
- [x] Modify existing tests to work correctly with JUnit5
- [ ] Improve the performance of existing tests with new features coming from JUnit5

**Comment by larsk21** [comment]
> Improve the performance of existing tests with new features coming from JUnit5

I made our random tests easier to understand with new features from JUnit 5. Are there any other performance improving features we should use?

**Comment by larsk21** [comment]
@gstuer ?
