### ISSUE TITLE
Precise error messages

### ISSUE THREAD

**Issue by LDAP** [kit-sdq/TimeSheetGenerator#77]
Currently the generator exits with messages like "Maximum working time without pause exceeded". 
A hint where the error occured would be very helpful (e.g. line in month.json or day).

**Comment by gstuer** [comment]
Hi @LDAP, you're right! We already fixed this issue and made the error messages a little more informative. This feature is going to be part of the next release version. Nevertheless, thank you for your contribution!
https://github.com/kit-sdq/TimeSheetGenerator/blob/b6e4d82c9a1f6894c795ab3bd1df8d0e2185ec45/src/main/java/checker/MiLoGChecker.java#L318
