### ISSUE TITLE
Improving the quality of the new Docker feature 

### ISSUE THREAD

**Issue by larsk21** [kit-sdq/TimeSheetGenerator#80]
The changes on the docker branch are a valuable addition to our application, but I would like to invest some time in the (software) quality of this feature. The improvements below are aiming to provide a consistent and stable UX and development workflow. This list is open for discussion and contributions are welcome.

**Build**
The build of the docker image should be tested and run stable. This is necessary if in the future the build is included as a task in Maven or a build pipeline.

**Release**
We have to decide on a release platform for the docker image. The two choices I have in mind are the Docker Hub and our GitHub release page.

*Pro Docker Hub*
- easy to install the image from the command line
- access without visiting the GitHub page

*Pro GitHub Release Page*
- same release platform as the executable jar file (single platform)
- one build process: building the jar, building the image, uploading both to GitHub
- consistent versioning is simple since all files for a release are uploaded at the same time
- building the image may be included in our Maven-based build process (if this is possible)
- required content can be loaded from the local index when the release build is running

**User Interface**
The user should interact with the docker script in the same way as with our java application directly. This includes specifying the path of the input and output files and executing commands such as displaying the version or the command line help.

Specifying the input and output files will be limited when executing the docker image directly since the files need to be in the specified source directory. When using the provided script though, the files should be copied from and to anywhere in the file system.

Using the GUI in combination with the docker image is out of scope for now, but it would be interesting to see if this is an option for the future.

**System Requirements**
Since we provide a script to execute the docker image on Windows, we should add a corresponding script for execution on Linux machine. This would probably be a bash script.
<br>
Feel free to add to this list and/or participate in the discussion.

**Comment by gstuer** [comment]
Unfortunately I'm not an expert on docker specific issues. As far as I'm concerned, changing completely to a new build and release platform is far more effort than necessary. Github, especially with the new free features, has everything we need to manage our project. Using the right actions should also make it extremely easy to provide a docker image automatically on release/commit. Is there anything important I wasn't taking into account here? @TomWerm do you have any additional suggestions concerning this issue?

**Comment by TomWerm** [comment]
@larsk21 
__Build__
Since the build depends on external resources, this is a hard to realize requirement. Own latex install files and scripts may be neccessary.
__Release__
@gstuer Or we provide the docker image without the jar and add it to the parameter list since the image does not depend on the version of the jar (unless some new latex libraries are required). 
__User Interface__
The script can be easily adapted to take the paths as parameters. The script can then copy the files into the current working directory.
Using the UI with the docker image is possible. The usability is limited since the paths cannot be chosen inside the docker container because it has its own file system (only mounted volumes are available).
__System Requirements__
The bash script should contain the same lines as the windows script since the docker run call is the same (only difference is the definition of variables).

**Comment by larsk21** [comment]
Thank you, now let me see if I can summarize what we need to do.

**Build**
It's clear that errors can always happen when relying on external sources that need to be downloaded in the build process. But since this could be run in a pipeline it should be at least mostly stable. (Maven for example downloads files as well, which works pretty well.) I would take a look at this and try to improve it, maybe updating the package mirrors before downloading could help.

**Release**
*pending*

**User Interface**
Using the UI with docker is probably possible, but not our focus at the moment. Since the command line interface will undergo some changes in the future, I would say it's only necessary to support specifying the input and output files for calling the TimeSheetGenerator. Those should however be allowed to lie anywhere on the file system.

My use case:
```
./user_build_pdf.sh ./global.json ./month_2020-02.json ../Arbeitszeitdokumentation/MiLoG_2020-02.pdf
```

@TomWerm, could you let us know if you're available for this and if so, update the script accordingly?

**System Requirements**
I agree. Since you said you're on a windows machine, I can create the bash file after you've updated the cmd file.

**Comment by larsk21** [comment]
After a strategy meeting I'm happy to give an update about the current status.

**Release**
The docker image will (for now) only be released on GitHub. This reduces the organizational effort and simplifies the release process until a more advanced building mechanism is available (see below). The release process will look as follows:
- the Java executable is built from the `stable` branch
- the docker image is built locally with the built Java executable
- the docker image is exported as an image archive
- the `jar` file, the docker image archive and the run script are uploaded as part of a release on GitHub

The process of using our app (with docker) is then:
- the user downloads the docker image archive and the run script
- the user imports the docker image with `docker load -i <file name>`
- the user starts the docker container with the run script

**Future plans**
We plan to build a continuous integration pipeline for our app in the future. As one part of this pipeline it's planned to build the docker image on DockerHub. In order to do this, we have to check on which account we could upload to DockerHub (for example a KIT-SDQ account).

**Questions**
If the image is released on DockerHub, how is the run script released? Is a run script necessary for copying the files or could this be included in the docker image somehow? If the run script is released on GitHub, but the image is released on DockerHub, how can we be sure that the versions match? If the run script uses a fixed version, we don't benefit from automatic updates.
