### ISSUE TITLE
Warnings caused by illegal reflective access

### ISSUE THREAD

**Issue by gstuer** [kit-sdq/TimeSheetGenerator#85]
The following warnings appear at build and runtime:

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/C:/Users/Mose/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.0/jackson-databind-2.10.0.jar) to field java.time.LocalDate.year
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by gstuer** [comment]
![image](https://user-images.githubusercontent.com/56889322/79637997-83ca6600-8183-11ea-8fb3-64172d279a29.png)

**Comment by larsk21** [comment]
This seems to be a known issue to the Jackson developers and is caused by the protections available with the new Java Platform Module System (Java 9+).

**Comment by larsk21** [comment]
Possible solution: Include Jackson JDK8 modules

[jackson-modules-java8](https://github.com/FasterXML/jackson-modules-java8)
